#' @title Collecting Google Earth Engine Data
#'
#' @description This function collects data from Google Earth Engine based on
#' the specified task.
#'
#' @param task [Mandatory] This object, generated by the \code{GenerateTask}
#' function, manages the update or (re)building operation.
#'
#' @param resolution [Optional] The resolution for hexagons. Default value is
#' \code{4}.
#'
#' @param scale [Optional] The scale for Earth Engine data extraction. Default
#' value is \code{10000}.
#'
#' @return An \code{sf} object containing the collected Google Earth Engine
#' data.
#'
#' @export
#'
#' @examples
#' # Example: Retrieve Google Earth Engine data using a task file
#' \dontrun{
#' result <- GetGEEData(task = task)
#' print(result)
#' }
#'
#' @import lubridate
#' @importFrom magrittr %>%
#' @importFrom cli cli_abort
#' @importFrom utils capture.output
#' @importFrom progress progress_bar
#' @importFrom sf st_transform st_as_sf st_join
#' @importFrom h3jsr polygon_to_cells cell_to_polygon
#' @importFrom rgee ee ee_Initialize ee_Authenticate ee_extract ee_as_sf
#' @importFrom rgee sf_as_ee
#'
GetGEEData <- function(task, resolution = 4, scale = 10000) {

  # ----------------------------------------------------------------------------
  # S1: User authentication for Google Earth Engine
  # ----------------------------------------------------------------------------

  # Specify the Earth Engine datasets and bands
  gee.info <- list(
    database = c("MODIS_061_MOD13A2", "`UCSB-CHG_CHIRPS_DAILY`"),
    band = c("NDVI", "precipitation")
  )

  # Attempt to initialize Earth Engine
  tryCatch({
    rgee.message <- capture.output(ee_Initialize())
  }, error = function(e) {
    cat(paste("Warning: Authentication is required. ", e$message, "\n"))

    # Attempt to authenticate and initialize again
    tryCatch({
      ee_Authenticate(quiet = TRUE)
      rgee.message <- capture.output(ee_Initialize())
    }, error = function(auth_error) {
      cat(paste("Error during authentication: ", auth_error$message, "\n"))
    })
  })

  cat(rgee.message[-c(1,length(rgee.message))], sep = "\n")
  cat("\n")

  # ----------------------------------------------------------------------------
  # S2: Definition of the 'DateSequence' function
  # ----------------------------------------------------------------------------

  DateSequence <- function(start.date, end.date, frequency) {
    if (frequency == "Daily") {
      date.sequence <- seq(start.date - 1L, end.date, by = "days")
    } else if (frequency == "Monthly") {
      # Subtracting one month from the start_date to get the 0th element
      date.sequence <- seq(as.Date(format(start.date, "%Y-%m-01")) - months(1),
                           end.date, by = "months")
    } else if (frequency == "Yearly") {
      date.sequence <- seq(as.Date(format(start.date, "%Y-01-01")) - months(12),
                           end.date, by = "years")
    } else {
      stop("Invalid frequency specified.")
    }
    return(date.sequence)
  }

  # ----------------------------------------------------------------------------
  # S3: Definition of the hexagonal bins for selected countries
  # ----------------------------------------------------------------------------

  # Remove "*" characters
  countries <- sub("\\*", "", task$MainCountries)
  datasets <- sub("\\*", "", task$MainDatasets)

  # Drop non-selected bands from the gee.info list
  gee.info <- list(
    database = gee.info$database[tolower(gee.info$band) %in%
                                   tolower(datasets)],
    band = gee.info$band[tolower(gee.info$band) %in%
                           tolower(datasets)]
  )

  country.features <- ee$FeatureCollection('USDOS/LSIB_SIMPLE/2017')$
    filter(ee$Filter$inList('country_na', as.list(countries)))$
    select('geometry', 'country_na')

  suppressMessages({
    geo.features <- ee_as_sf(country.features)
  })

  # Split country geometries into individual hexagonal bins
  for (i in 1:nrow(geo.features)) {

    geometry <- st_transform(geo.features$geometry[i], crs = 4326)
    hexagon.ids <- polygon_to_cells(geometry, res = resolution)
    hexagon.grid <- cell_to_polygon(hexagon.ids)

    if (i == 1L) {
      hexagon <- as.data.frame(hexagon.grid)
      hexagon$country <- geo.features$country_na[i]
      hexagon$h3 <- unlist(hexagon.ids)
      hexagons <- hexagon[,c(2,3,1)]
    } else {
      hexagon <- as.data.frame(hexagon.grid)
      hexagon$country <- geo.features$country_na[i]
      hexagon$h3 <- unlist(hexagon.ids)
      hexagon <- hexagon[,c(2,3,1)]
      hexagons <- rbind(hexagons,hexagon)
    }
  }

  hexagons.ee <- st_as_sf(hexagons) %>% sf_as_ee()

  # ----------------------------------------------------------------------------
  # S4: Collect Google Earth Engine data (main session)
  # ----------------------------------------------------------------------------

  if (task$MainSession) {
    for (i in 1:length(task$MainStartDate)){

      main.sequence <- DateSequence(as.Date(task$MainStartDate[[i]]),
                                    as.Date(task$MainEndDate[[i]]),
                                    task$Frequency)

      if (i == 1) {

        # Create a progress bar
        total_iterations <- length(task$MainStartDate) *
          (length(main.sequence)-1) * length(gee.info$band)
        pb <- progress_bar$new(
          format = "Main Session: [:bar] :percent, eta: :eta",
          total = total_iterations,
          width= 80,
          clear = FALSE
        )
      }

      for (j in 1:(length(main.sequence)-1)) {

        from.date <- format(main.sequence[j], "%Y-%m-%d")
        to.date <- format(main.sequence[j+1], "%Y-%m-%d")

        for (k in 1:length(gee.info$band)) {

          rgee.expression <- paste0(
            "ee$ImageCollection$Dataset$", gee.info$database[k], "$",
            "select('", gee.info$band[k], "')$",
            "filterDate('", from.date, "', '", to.date, "')$",
            "mean()$",
            "rename('value')"
          )

          image <- eval(parse(text = rgee.expression))

          sink.message <- capture.output(
            band.stats <- ee_extract(
              x = image,
              y = hexagons.ee,
              fun = ee$Reducer$mean(),
              sf = TRUE,
              scale = scale,
              quiet = TRUE)
          )

          band.stats$band <- gee.info$band[k]
          band.stats <- band.stats[, c(1, 2, 5, 3, 4)]

          pb$tick()

          if (k == 1L){
            bands.stats <- band.stats
          } else {
            bands.stats <- rbind(bands.stats, band.stats)
          }

        }

        bands.stats$from_date <- from.date
        bands.stats$to_date <- to.date
        bands.stats$frequency <- tolower(task$Frequency)

        if (!exists("gee.data")){
          gee.data <- bands.stats
        } else {
          gee.data <- rbind(gee.data, bands.stats)
          rm(bands.stats)
        }
      }
    }
  }

  # ----------------------------------------------------------------------------
  # S5: Collect Google Earth Engine data (supplementary session)
  # ----------------------------------------------------------------------------

  if (task$SuppSession > 1L) {

    cat("\n")
    supp.sequence <- DateSequence(as.Date(task$SuppDateRange[1]),
                                        as.Date(task$SuppDateRange[2]),
                                        task$Frequency)

    for (i in 1:length(task$SuppDatasets)) {

      supp.hexagons <- hexagons[hexagons$country %in% task$SuppCountries[[i]],]
      supp.hexagons.ee <- st_as_sf(supp.hexagons) %>% sf_as_ee()

      supp.info <- list(
        database = gee.info$database[tolower(gee.info$band) %in%
                                       tolower(task$SuppDataset[[i]])],
        band = gee.info$band[tolower(gee.info$band) %in%
                               tolower(task$SuppDataset[[i]])]
      )

      if (i == 1L) {

        # Create a progress bar
        total_iterations <- (length(supp.sequence)-1L) *
          length(task$SuppDatasets)
        pb <- progress_bar$new(
          format = "Supp Session: [:bar] :percent, eta: :eta",
          total = total_iterations,
          width= 80,
          clear = FALSE
        )
      }

      for (j in 1:(length(supp.sequence)-1)) {

        from.date <- format(supp.sequence[j], "%Y-%m-%d")
        to.date <- format(supp.sequence[j+1], "%Y-%m-%d")

        for (k in 1:length(supp.info$band)) {

          rgee.expression <- paste0(
            "ee$ImageCollection$Dataset$", supp.info$database[k], "$",
            "select('", supp.info$band[k], "')$",
            "filterDate('",from.date,"', '",to.date,"')$",
            "mean()$",
            "rename('value')"
          )

          image <- eval(parse(text = rgee.expression))

          sink.message <- capture.output(
            band.stats <- ee_extract(
              x = image,
              y = hexagons.ee,
              fun = ee$Reducer$mean(),
              sf = TRUE,
              scale = scale,
              quiet = TRUE)
          )

          pb$tick()

          band.stats$band <- supp.info$band[k]
          band.stats <- band.stats[, c(1, 2, 5, 3, 4)]

          if (k == 1L){
            bands.stats <- band.stats
          } else {
            bands.stats <- rbind(bands.stats, band.stats)
          }
        }

        bands.stats$from_date <- from.date
        bands.stats$to_date <- to.date
        bands.stats$frequency <- tolower(task$Frequency)

        if (!exists("gee.data")){
          gee.data <- bands.stats
        } else {
          gee.data <- rbind(gee.data, bands.stats)
          rm(bands.stats)
        }
      }
    }
  }

  return(gee.data)
}
